<?php
/**
 * @file
 * Main logic file for the module
 */

/*
 * TODO
  * 1.    Display a block that shows the time the user last logged in with a message of “You last logged in at “
  * 2.    In the user’s current time-zone
  * 3.    Have the block automatically be placed in left siderail region (if available)
  * 4.    Make sure that the block is not visible for non-logged in users.
  * 5.    Make this a panels content type instead of a block
  * 6.    Allow the message to be configured per user - display a different message per user.
  * 7.    Frontend Javascript should collapse (animated) the block after 10 seconds.
 */

/**
 * Implements hook_menu()ß
 */

/**
 * Implement hook_block_info()
 */
function twc_block_demo_block_info() {
  $blocks['user_last_login'] = array(
    'info' => t("User last login"),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    //'region'
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function twc_block_demo_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case "user_last_login":
      $block['subject'] = t("Welcome");
      $block['content'] = ""; //TODO
      break;
  }

  return $block;
}

/**
 * Implements hook_theme()
 */
/*function twc_block_demo_theme($existing, $type, $theme, $path) {

}*/

/**
 * This is the actual display logic for the block in question. It will return
 * the markup for the block from a theme() call, or it will return nothing if the
 * associated user is a "anonymous user".
 */
function twc_block_demo_output() {
  global $user;

  dpm($user, "User Object");
}

/**
 * Returns the last time the user logged in. To get this time, we look up
 * the "login" value for that user in the globalized $user object, and convert it
 * from a timestamp value to a human readable value (fuzzy)
 */
function twc_block_demo_return_last_login_time($user) {
  //global $user;
}
