<?php
/**
 * @file
 * Main logic file for the module
 */

/*
 * TODO
  * 1.    Display a block that shows the time the user last logged in with a message of “You last logged in at “
  * 2.    In the user’s current time-zone
  * 3.    Have the block automatically be placed in left siderail region (if available)
  * 4.    Make sure that the block is not visible for non-logged in users.
  * 5.    Make this a panels content type instead of a block
  * 6.    Allow the message to be configured per user - display a different message per user.
  * 7.    Frontend Javascript should collapse (animated) the block after 10 seconds.
 */

/**
 * Implements hook_menu()
 */
function twc_block_demo() {
  $items['settings/welcome'] = array(
    'title' => t('Welcome Message Settings'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => 'twc_block_demo_form',
    'file' => 'twc_block_demo.form.inc'
  );

  return $items;
}

/**
 * Implement hook_block_info()
 */
function twc_block_demo_block_info() {
  $blocks['user_last_login'] = array(
    'info' => t("User last login"),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    //'region'
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function twc_block_demo_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case "user_last_login":
      $block['subject'] = t("Welcome");
      $block['content'] = twc_block_demo_output(); //TODO
      break;
  }

  return $block;
}

/**
 * This is the actual display logic for the block in question. It will return
 * the markup for the block from a theme() call, or it will return nothing if the
 * associated user is a "anonymous user".
 */
function twc_block_demo_output() {
  global $user;

  dpm($user, "User Object");

  // If the User has the role of "Authenticated User", run the time gathering
  // logic. Otherwise, exit and return null item.
  if(in_array("authenticated user", $user->roles) ) {
    return "Found";
  } else {
    return null;
  }
}

/**
 * Returns the last time the user logged in. To get this time, we look up
 * the "login" value for that user in the globalized $user object, and convert it
 * from a timestamp value to a human readable value (fuzzy)
 */
function twc_block_demo_return_last_login_time($user) {
  // Look up the database to see if a user has a custom message and use it
  // else, fall back and use the default
  $results = twc_block_demo_get_custom_welcome_message($user->uid);

  if(sizeof($results) > 0) {
    //TODO
  } else {
    $message = "You last logged in at ";
  }

  //Friendly format the last time logged in
  $last_logged_in = twc_block_demo_format_time($user->login);
}

/**
 * TODO documentation
 * @param  [type] $user_id [description]
 * @return [type]          [description]
 */
function twc_block_demo_get_custom_welcome_message($user_id) {

}

/**
 * TODO Documentation
 * @param  [type] $user_login_time [description]
 * @return [type]                  [description]
 */
function twc_block_demo_format_time($user_login_time) {
  // Return a human readable date when the user logged in


}
